version: '3.1'

services:
  postgres:
    image: postgres:10-alpine
    environment:
      POSTGRES_USER: stamina
      POSTGRES_PASSWORD: stamina
    ports:
      - 5432:5432
    volumes:
      - ../schema:/docker-entrypoint-initdb.d